import prism from 'markdown-it-prism';

// import 'prismjs/components/prism-abap.js';
// import 'prismjs/components/prism-actionscript.js';
// import 'prismjs/components/prism-ada.js';
// import 'prismjs/components/prism-apacheconf.js';
// import 'prismjs/components/prism-apl.js';
// import 'prismjs/components/prism-applescript.js';
// import 'prismjs/components/prism-arduino.js';
// import 'prismjs/components/prism-arff.js';
// import 'prismjs/components/prism-asciidoc.js';
// import 'prismjs/components/prism-asm6502.js';
// import 'prismjs/components/prism-aspnet.js';
// import 'prismjs/components/prism-autohotkey.js';
// import 'prismjs/components/prism-autoit.js';
import 'prismjs/components/prism-bash.js';
// import 'prismjs/components/prism-basic.js';
// import 'prismjs/components/prism-batch.js';
// import 'prismjs/components/prism-bison.js';
// import 'prismjs/components/prism-brainfuck.js';
// import 'prismjs/components/prism-bro.js';
import 'prismjs/components/prism-c.js';
// import 'prismjs/components/prism-clike.js';
// import 'prismjs/components/prism-clojure.js';
// import 'prismjs/components/prism-coffeescript.js';
// import 'prismjs/components/prism-core.js';
import 'prismjs/components/prism-cpp.js';
// import 'prismjs/components/prism-crystal.js';
import 'prismjs/components/prism-csharp.js';
// import 'prismjs/components/prism-csp.js';
import 'prismjs/components/prism-css.js';
import 'prismjs/components/prism-css-extras.js';
// import 'prismjs/components/prism-d.js';
// import 'prismjs/components/prism-dart.js';
import 'prismjs/components/prism-diff.js';
// import 'prismjs/components/prism-django.js';
// import 'prismjs/components/prism-docker.js';
// import 'prismjs/components/prism-eiffel.js';
// import 'prismjs/components/prism-elixir.js';
// import 'prismjs/components/prism-elm.js';
// import 'prismjs/components/prism-erb.js';
// import 'prismjs/components/prism-erlang.js';
// import 'prismjs/components/prism-flow.js';
// import 'prismjs/components/prism-fortran.js';
// import 'prismjs/components/prism-fsharp.js';
// import 'prismjs/components/prism-gedcom.js';
// import 'prismjs/components/prism-gherkin.js';
// import 'prismjs/components/prism-git.js';
// import 'prismjs/components/prism-glsl.js';
// import 'prismjs/components/prism-go.js';
// import 'prismjs/components/prism-graphql.js';
// import 'prismjs/components/prism-groovy.js';
// import 'prismjs/components/prism-haml.js';
// import 'prismjs/components/prism-handlebars.js';
import 'prismjs/components/prism-haskell.js';
// import 'prismjs/components/prism-haxe.js';
// import 'prismjs/components/prism-hpkp.js';
// import 'prismjs/components/prism-hsts.js';
// import 'prismjs/components/prism-http.js';
// import 'prismjs/components/prism-ichigojam.js';
// import 'prismjs/components/prism-icon.js';
// import 'prismjs/components/prism-inform7.js';
// import 'prismjs/components/prism-ini.js';
// import 'prismjs/components/prism-io.js';
// import 'prismjs/components/prism-j.js';
import 'prismjs/components/prism-java.js';
import 'prismjs/components/prism-javascript.js';
// import 'prismjs/components/prism-jolie.js';
// import 'prismjs/components/prism-json.js';
import 'prismjs/components/prism-jsx.js';
// import 'prismjs/components/prism-julia.js';
// import 'prismjs/components/prism-keyman.js';
// import 'prismjs/components/prism-kotlin.js';
// import 'prismjs/components/prism-latex.js';
// import 'prismjs/components/prism-less.js';
// import 'prismjs/components/prism-liquid.js';
// import 'prismjs/components/prism-lisp.js';
// import 'prismjs/components/prism-livescript.js';
// import 'prismjs/components/prism-lolcode.js';
// import 'prismjs/components/prism-lua.js';
// import 'prismjs/components/prism-makefile.js';
import 'prismjs/components/prism-markdown.js';
// import 'prismjs/components/prism-markup-templating.js';
// import 'prismjs/components/prism-markup.js';
// import 'prismjs/components/prism-matlab.js';
// import 'prismjs/components/prism-mel.js';
// import 'prismjs/components/prism-mizar.js';
// import 'prismjs/components/prism-monkey.js';
// import 'prismjs/components/prism-n4js.js';
// import 'prismjs/components/prism-nasm.js';
// import 'prismjs/components/prism-nginx.js';
// import 'prismjs/components/prism-nim.js';
// import 'prismjs/components/prism-nix.js';
// import 'prismjs/components/prism-nsis.js';
// import 'prismjs/components/prism-objectivec.js';
// import 'prismjs/components/prism-ocaml.js';
// import 'prismjs/components/prism-opencl.js';
// import 'prismjs/components/prism-oz.js';
// import 'prismjs/components/prism-parigp.js';
// import 'prismjs/components/prism-parser.js';
// import 'prismjs/components/prism-pascal.js';
// import 'prismjs/components/prism-perl.js';
// import 'prismjs/components/prism-php.js';
// import 'prismjs/components/prism-php-extras.js';
// import 'prismjs/components/prism-plsql.js';
import 'prismjs/components/prism-powershell.js';
// import 'prismjs/components/prism-processing.js';
// import 'prismjs/components/prism-prolog.js';
// import 'prismjs/components/prism-properties.js';
// import 'prismjs/components/prism-protobuf.js';
// import 'prismjs/components/prism-pug.js';
// import 'prismjs/components/prism-puppet.js';
// import 'prismjs/components/prism-pure.js';
import 'prismjs/components/prism-python.js';
// import 'prismjs/components/prism-q.js';
// import 'prismjs/components/prism-qore.js';
import 'prismjs/components/prism-r.js';
// import 'prismjs/components/prism-reason.js';
// import 'prismjs/components/prism-renpy.js';
// import 'prismjs/components/prism-rest.js';
// import 'prismjs/components/prism-rip.js';
// import 'prismjs/components/prism-roboconf.js';
// import 'prismjs/components/prism-ruby.js';
// import 'prismjs/components/prism-rust.js';
// import 'prismjs/components/prism-sas.js';
// import 'prismjs/components/prism-sass.js';
// import 'prismjs/components/prism-scala.js';
import 'prismjs/components/prism-scheme.js';
// import 'prismjs/components/prism-scss.js';
// import 'prismjs/components/prism-smalltalk.js';
// import 'prismjs/components/prism-smarty.js';
// import 'prismjs/components/prism-soy.js';
// import 'prismjs/components/prism-sql.js';
// import 'prismjs/components/prism-stylus.js';
// import 'prismjs/components/prism-swift.js';
// import 'prismjs/components/prism-tap.js';
// import 'prismjs/components/prism-tcl.js';
// import 'prismjs/components/prism-textile.js';
// import 'prismjs/components/prism-tsx.js';
// import 'prismjs/components/prism-tt2.js';
// import 'prismjs/components/prism-twig.js';
import 'prismjs/components/prism-typescript.js';
// import 'prismjs/components/prism-vbnet.js';
// import 'prismjs/components/prism-velocity.js';
// import 'prismjs/components/prism-verilog.js';
// import 'prismjs/components/prism-vhdl.js';
// import 'prismjs/components/prism-vim.js';
// import 'prismjs/components/prism-visual-basic.js';
// import 'prismjs/components/prism-wasm.js';
// import 'prismjs/components/prism-wiki.js';
// import 'prismjs/components/prism-xeora.js';
// import 'prismjs/components/prism-xojo.js';
// import 'prismjs/components/prism-xquery.js';
import 'prismjs/components/prism-yaml.js';

import 'prismjs/plugins/line-highlight/prism-line-highlight.js';

export default prism;
